OPENQASM 2.0;
include "qelib1.inc";

qreg qubit[12];
creg cbits[11];
h qubit[0];
h qubit[1];
h qubit[2];
h qubit[3];
h qubit[4];
h qubit[5];
h qubit[6];
h qubit[7];
h qubit[8];
h qubit[9];
h qubit[10];
h qubit[11];
z qubit[11];
cx qubit[0],qubit[11];
h qubit[0];
cx qubit[1],qubit[11];
measure qubit[0] -> cbits[0];
h qubit[1];
cx qubit[2],qubit[11];
measure qubit[1] -> cbits[1];
h qubit[2];
cx qubit[3],qubit[11];
measure qubit[2] -> cbits[2];
h qubit[3];
cx qubit[4],qubit[11];
measure qubit[3] -> cbits[3];
h qubit[4];
cx qubit[5],qubit[11];
measure qubit[4] -> cbits[4];
h qubit[5];
cx qubit[6],qubit[11];
measure qubit[5] -> cbits[5];
h qubit[6];
cx qubit[7],qubit[11];
measure qubit[6] -> cbits[6];
h qubit[7];
cx qubit[8],qubit[11];
measure qubit[7] -> cbits[7];
h qubit[8];
cx qubit[9],qubit[11];
measure qubit[8] -> cbits[8];
h qubit[9];
cx qubit[10],qubit[11];
measure qubit[9] -> cbits[9];
h qubit[10];
h qubit[11];
measure qubit[10] -> cbits[10];
